### ISSUE TITLE
안녕하세요? 개발자님!

### ISSUE THREAD

**Issue by KnowProblem** [JaehyeonSK/Android-AR-Pedestrian-Navigation#2]
안녕하세요? 개발자님. 증강현실에 관심이 있는 사람입니다.
좋은 내용이라 공부하고 있는데 프로젝트 경로를 찾아봐도 androidmanifest.xml를 찾을수가 없습니다.

좋은 방법을 알려주시면 감사하겠습니다.

**Comment by JaehyeonSK** [comment]
업로드 하였습니다.
